jasypt:
  encryptor:
    password: sccf-combanc #根密钥

server:
  tomcat:
    max-http-post-size: 2097152
    max-threads: 500
    min-spare-threads: 50
    port-header: X-Forwarded-Port
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-FORWARDED-FOR
    uri-encoding: UTF-8

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null #对象为null的，不输出
  redis:
    remote: true         #是否是开启缓存
    timeout: 6000           # 连接超时时长（毫秒）
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接
    database: 0
    host: 127.0.0.1
    port: 6379
    password:      # 密码（默认为空）
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: vaellys
    password: vaellys
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
    encoding:
      enabled: true
      charset: UTF-8
      force: true

cache:
  redis:
    expiration: 3600

ribbon:
  eager-load:
    enabled: true
    clients: sccf-auth-server,sccf-business-admin
  Httpclient:
    enable: false
  OkHttp:
    enable: true
  ReadTimeout: 10000 # 请求处理的超时时间
  ConnectTimeout: 10000 # 请求连接的超时时间
  MaxAutoRetries: 1 # 对当前实例的重试次数
  MaxAutoRetriesNextServer: 2 # 切换实例的重试次数
  OkToRetryOnAllOperations: true # 对所有操作请求都进行重试

  
feign:
  hystrix:
    enabled: true
  okhttp:
    enable: true
  httpclient:
    enable: false
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 500 #并发执行的最大线程数，默认10
      maxQueueSize: 1000 #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 800 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 # 超时时间（默认1000ms，单位：ms） hystrix的超时时间必须大于ribbon的超时时间
               
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false