server:
  port: 1003

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: vaellys
    password: vaellys
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1.0 #日志记录发送给采集器的概率,配置成1全量收集日志

zuul:
  ribbon:
    eager-load:
      enabled: true #开启Ribbon的饥饿加载模式
      clients: sccf-auth-server,sccf-business-admin #指定需要饥饿加载的客户端名称、服务名
  ignoredServices: '*'
  retryable: true # 开启重试
  sensitiveHeaders: #允许header携带cookie等信息
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    sccf-auth-server:
      path: /auth/**
      serviceId: sccf-auth-server
      stripPrefix: true
      sensitiveHeaders:
    sccf-business-admin:
      path: /admin/**
      serviceId: sccf-business-admin
      stripPrefix: true
      sensitiveHeaders:
  ratelimit:
    key-prefix: sccf-ratelimite
    enabled: true
    repository: REDIS
    behind-proxy: true
    policies:
      sccf-business-admin:
        limit: 100
        quota: 100
        refresh-interval: 3 #3秒内允许300个访问，平均每个请求2秒，并且要求总请求时间小于2400秒

security:
  validate:
    code: false
  sessions: stateless
  oauth2:
    client:
      client-id: ENC(legvbZ4KwfYyIuf/20Mhdklrj7pC4val)
      client-secret: ENC(ib8sQVQ8djle786XDhprWw==)
    resource:
      loadBalanced: true
      token-info-uri: ${security.auth.server}/oauth/check-token #由资源服务器用来解码访问令牌
      service-id: sccf-gateway-server
      jwt:
         key-uri: ${security.auth.server}/oauth/token_key #使用JWT令牌，RSA公开密钥可以用于令牌验证
         #key-value: ENC(fmVD9Jt6YXP9Q+KBPU8/1cWgKn5WhlGuD10SzFADNz4=)
#security:
#  validate:
#    code: false
#  sessions: stateless
#  oauth2:
#    resource:
#      loadBalanced: true
#      user-info-uri: http://system-auth-server/user
#      prefer-token-info: false
#      service-id: system-gateway-server
# 上述做法将权限认证和网关解耦、建议采用RSA加密验证方式

urls:
  collects:
    - /auth/**
    - /swagger-resources/**
    - /swagger-ui.html
    - /*/v2/api-docs
    - /swagger/api-docs
    - /webjars/**

logging:
  config: classpath:logback.xml